/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frames;

import static frames.SetConnection.personalConfig;
import java.io.File;
import java.io.IOException;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import myClass.Log;
import org.ini4j.Ini;

/**
 *
 * @author gerda.modarres
 */
public class SelectMarker extends javax.swing.JFrame {
    
    String defaultPath = null;
    Log my_log;
    
    static String markerSql = null;

    /**
     * Creates new form SelectMarker
     */
    public SelectMarker() {
        initComponents();
        getIniData();
        jPanel1.getRootPane().setDefaultButton(btn_set);
    }

    public void getIniData() {
        Ini ini;
        try {
            //ini = new Ini(new File("config.ini")); // TEST
            ini = new Ini(new File(personalConfig));  // toggle 1/1
            //ini = new Ini(new File("C:\\Users\\gerda.modarres\\Desktop\\pat_DB\\config.ini"));
            String dp = ini.get("defaultpath", "path");
            this.defaultPath = dp;
        } catch (IOException ex) {
            Logger.getLogger(SetConnection.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btn_set = new javax.swing.JButton();
        btn_load = new javax.swing.JButton();
        btn_save = new javax.swing.JButton();
        lbl_selName = new javax.swing.JLabel();
        txt_nameSetting = new javax.swing.JTextField();
        btn_clear = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        chk_marker39 = new javax.swing.JCheckBox();
        chk_marker40 = new javax.swing.JCheckBox();
        chk_marker43 = new javax.swing.JCheckBox();
        chk_nonlin = new javax.swing.JCheckBox();
        chk_marker38 = new javax.swing.JCheckBox();
        chk_marker47 = new javax.swing.JCheckBox();
        chk_marker48 = new javax.swing.JCheckBox();
        chk_marker37 = new javax.swing.JCheckBox();
        chk_marker36 = new javax.swing.JCheckBox();
        chk_marker42 = new javax.swing.JCheckBox();
        chk_marker45 = new javax.swing.JCheckBox();
        chk_marker44 = new javax.swing.JCheckBox();
        chk_marker49 = new javax.swing.JCheckBox();
        chk_marker41 = new javax.swing.JCheckBox();
        chk_marker46 = new javax.swing.JCheckBox();
        jPanel3 = new javax.swing.JPanel();
        chk_marker34 = new javax.swing.JCheckBox();
        chk_marker24 = new javax.swing.JCheckBox();
        chk_marker26 = new javax.swing.JCheckBox();
        chk_marker31 = new javax.swing.JCheckBox();
        chk_marker33 = new javax.swing.JCheckBox();
        chk_marker27 = new javax.swing.JCheckBox();
        chk_marker28 = new javax.swing.JCheckBox();
        chk_marker22 = new javax.swing.JCheckBox();
        chk_marker35 = new javax.swing.JCheckBox();
        chk_marker30 = new javax.swing.JCheckBox();
        chk_marker29 = new javax.swing.JCheckBox();
        chk_myelo = new javax.swing.JCheckBox();
        chk_marker23 = new javax.swing.JCheckBox();
        chk_marker32 = new javax.swing.JCheckBox();
        chk_marker25 = new javax.swing.JCheckBox();
        jPanel4 = new javax.swing.JPanel();
        chk_marker15 = new javax.swing.JCheckBox();
        chk_marker20 = new javax.swing.JCheckBox();
        chk_marker21 = new javax.swing.JCheckBox();
        chk_marker14 = new javax.swing.JCheckBox();
        chk_marker18 = new javax.swing.JCheckBox();
        chk_marker19 = new javax.swing.JCheckBox();
        chk_marker17 = new javax.swing.JCheckBox();
        chk_Tlymph = new javax.swing.JCheckBox();
        chk_marker16 = new javax.swing.JCheckBox();
        chk_marker12 = new javax.swing.JCheckBox();
        chk_marker13 = new javax.swing.JCheckBox();
        jPanel5 = new javax.swing.JPanel();
        chk_marker5 = new javax.swing.JCheckBox();
        chk_marker10 = new javax.swing.JCheckBox();
        chk_marker3 = new javax.swing.JCheckBox();
        chk_marker2 = new javax.swing.JCheckBox();
        chk_marker7 = new javax.swing.JCheckBox();
        chk_Blymph = new javax.swing.JCheckBox();
        chk_marker9 = new javax.swing.JCheckBox();
        chk_marker1 = new javax.swing.JCheckBox();
        chk_marker4 = new javax.swing.JCheckBox();
        chk_marker6 = new javax.swing.JCheckBox();
        chk_marker8 = new javax.swing.JCheckBox();
        chk_marker11 = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        btn_set.setBackground(new java.awt.Color(0, 140, 140));
        btn_set.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ico/check_s.png"))); // NOI18N
        btn_set.setText("set marker");
        btn_set.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_setActionPerformed(evt);
            }
        });

        btn_load.setBackground(new java.awt.Color(51, 153, 255));
        btn_load.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ico/open-file-icon.png"))); // NOI18N
        btn_load.setText("<html> <center> load<br>selection</center></html>");
        btn_load.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_loadActionPerformed(evt);
            }
        });

        btn_save.setBackground(new java.awt.Color(255, 153, 0));
        btn_save.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ico/Floppy-Small-icon.png"))); // NOI18N
        btn_save.setText("<html> <center> save<br>selection</center></html>");
        btn_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_saveActionPerformed(evt);
            }
        });

        lbl_selName.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbl_selName.setForeground(new java.awt.Color(102, 153, 255));
        lbl_selName.setText("setting:");

        btn_clear.setBackground(new java.awt.Color(153, 153, 153));
        btn_clear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ico/Actions-edit-clear-list-icon.png"))); // NOI18N
        btn_clear.setText("clear");
        btn_clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_clearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(lbl_selName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_save, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_set, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_load, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_nameSetting, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_clear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_set, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(btn_save, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_load, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(lbl_selName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_nameSetting, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_clear)
                .addContainerGap())
        );

        chk_marker39.setText("HLADR");

        chk_marker40.setText("CD11a");

        chk_marker43.setText("CD44");

        chk_nonlin.setText("non-lineage");
        chk_nonlin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chk_nonlinActionPerformed(evt);
            }
        });

        chk_marker38.setText("CD45");

        chk_marker47.setText("CD184");

        chk_marker48.setText("NG2");

        chk_marker37.setText("CD38");

        chk_marker36.setText("CD34");

        chk_marker42.setText("CD36");

        chk_marker45.setText("CD99");

        chk_marker44.setText("CD56");

        chk_marker49.setText("CD371");

        chk_marker41.setText("CD11b");

        chk_marker46.setText("CD123");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(chk_marker49)
                        .addComponent(chk_marker48)
                        .addComponent(chk_marker47)
                        .addComponent(chk_marker46)
                        .addComponent(chk_marker45)
                        .addComponent(chk_marker44)
                        .addComponent(chk_marker42)
                        .addComponent(chk_marker41)
                        .addComponent(chk_marker40)
                        .addComponent(chk_marker39)
                        .addComponent(chk_marker37)
                        .addComponent(chk_marker36)
                        .addComponent(chk_marker38)
                        .addComponent(chk_marker43))
                    .addComponent(chk_nonlin, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(chk_nonlin)
                .addGap(3, 3, 3)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(chk_marker37)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(chk_marker38))
                    .addComponent(chk_marker36))
                .addGap(0, 0, 0)
                .addComponent(chk_marker39)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chk_marker40)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chk_marker41)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chk_marker42)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chk_marker43)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chk_marker44)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chk_marker45)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chk_marker46)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chk_marker47)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chk_marker48)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chk_marker49)
                .addContainerGap())
        );

        chk_marker34.setText("CD71");

        chk_marker24.setText("CD117");

        chk_marker26.setText("CD33");

        chk_marker31.setText("CD64");

        chk_marker33.setText("CD61");

        chk_marker27.setText("CD15");

        chk_marker28.setText("CD65");

        chk_marker22.setText("MPO");

        chk_marker35.setText("CD133");

        chk_marker30.setText("CD11c");

        chk_marker29.setText("CD14");

        chk_myelo.setText("myeloisch");
        chk_myelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chk_myeloActionPerformed(evt);
            }
        });

        chk_marker23.setText("LZ");

        chk_marker32.setText("CD41");

        chk_marker25.setText("CD13");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(chk_marker24, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(chk_marker23, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(chk_marker22, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(chk_marker25, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(chk_marker26, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(chk_marker27, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(chk_marker28)
                        .addComponent(chk_marker29)
                        .addComponent(chk_marker30)
                        .addComponent(chk_marker31)
                        .addComponent(chk_marker32)
                        .addComponent(chk_marker33)
                        .addComponent(chk_marker34)
                        .addComponent(chk_marker35))
                    .addComponent(chk_myelo, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(chk_myelo)
                .addGap(3, 3, 3)
                .addComponent(chk_marker22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chk_marker23)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chk_marker24)
                .addGap(0, 0, 0)
                .addComponent(chk_marker25)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chk_marker26)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chk_marker27)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chk_marker28)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chk_marker29)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chk_marker30)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chk_marker31)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chk_marker32)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chk_marker33)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chk_marker34)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chk_marker35)
                .addContainerGap())
        );

        chk_marker15.setText("CD5");

        chk_marker20.setText("TCRab");

        chk_marker21.setText("TCRgd");

        chk_marker14.setText("CD2");

        chk_marker18.setText("CD4");

        chk_marker19.setText("CD8");

        chk_marker17.setText("sCD3");

        chk_Tlymph.setText("T-lymphoid");
        chk_Tlymph.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chk_TlymphActionPerformed(evt);
            }
        });

        chk_marker16.setText("CD1a");

        chk_marker12.setText("iCD3");

        chk_marker13.setText("CD7");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(chk_marker12, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(chk_marker13, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(chk_marker14, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(chk_marker15, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(chk_marker16, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(chk_marker17, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(chk_marker18, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(chk_marker20, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(chk_marker19, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(chk_marker21, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(chk_Tlymph, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(chk_Tlymph)
                .addGap(3, 3, 3)
                .addComponent(chk_marker12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chk_marker13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chk_marker14)
                .addGap(0, 0, 0)
                .addComponent(chk_marker15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chk_marker16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chk_marker17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chk_marker18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chk_marker19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chk_marker20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chk_marker21)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        chk_marker5.setText("CD20");

        chk_marker10.setText("ikappa");

        chk_marker3.setText("iCD79a");

        chk_marker2.setText("iCD22");

        chk_marker7.setText("CD24");

        chk_Blymph.setText("B-lymphoid");
        chk_Blymph.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chk_BlymphActionPerformed(evt);
            }
        });

        chk_marker9.setText("iIgM");

        chk_marker1.setText("CD19");

        chk_marker4.setText("CD10");

        chk_marker6.setText("CD22");

        chk_marker8.setText("CRLF2");

        chk_marker11.setText("ilambda");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(chk_marker1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(chk_marker2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(chk_marker3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(chk_marker4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(chk_marker5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(chk_marker6, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(chk_marker7, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(chk_marker8, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(chk_marker9, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(chk_marker10, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(chk_Blymph, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(chk_marker11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(chk_Blymph)
                .addGap(3, 3, 3)
                .addComponent(chk_marker1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chk_marker2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chk_marker3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chk_marker4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chk_marker5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chk_marker6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chk_marker7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chk_marker8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chk_marker9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chk_marker10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chk_marker11)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getAccessibleContext().setAccessibleName("SelectMarker");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void chk_BlymphActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chk_BlymphActionPerformed
        if (chk_Blymph.isSelected()) {
            chk_marker1.setSelected(true);
            chk_marker2.setSelected(true);
            chk_marker3.setSelected(true);
            chk_marker4.setSelected(true);
            chk_marker5.setSelected(true);
            chk_marker6.setSelected(true);
            chk_marker7.setSelected(true);
            chk_marker8.setSelected(true);
            chk_marker9.setSelected(true);
            chk_marker10.setSelected(true);
            chk_marker11.setSelected(true);
        } else {
            chk_marker1.setSelected(false);
            chk_marker2.setSelected(false);
            chk_marker3.setSelected(false);
            chk_marker4.setSelected(false);
            chk_marker5.setSelected(false);
            chk_marker6.setSelected(false);
            chk_marker7.setSelected(false);
            chk_marker8.setSelected(false);
            chk_marker9.setSelected(false);
            chk_marker10.setSelected(false);
            chk_marker11.setSelected(false);
        }
    }//GEN-LAST:event_chk_BlymphActionPerformed

    private void chk_TlymphActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chk_TlymphActionPerformed
        if (chk_Tlymph.isSelected()) {
            chk_marker12.setSelected(true);
            chk_marker13.setSelected(true);
            chk_marker14.setSelected(true);
            chk_marker15.setSelected(true);
            chk_marker16.setSelected(true);
            chk_marker17.setSelected(true);
            chk_marker18.setSelected(true);
            chk_marker19.setSelected(true);
            chk_marker20.setSelected(true);
            chk_marker21.setSelected(true);
        } else {
            chk_marker12.setSelected(false);
            chk_marker13.setSelected(false);
            chk_marker14.setSelected(false);
            chk_marker15.setSelected(false);
            chk_marker16.setSelected(false);
            chk_marker17.setSelected(false);
            chk_marker18.setSelected(false);
            chk_marker19.setSelected(false);
            chk_marker20.setSelected(false);
            chk_marker21.setSelected(false);
        }
    }//GEN-LAST:event_chk_TlymphActionPerformed

    private void chk_myeloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chk_myeloActionPerformed
        if (chk_myelo.isSelected()) {
            chk_marker22.setSelected(true);
            chk_marker23.setSelected(true);
            chk_marker24.setSelected(true);
            chk_marker25.setSelected(true);
            chk_marker26.setSelected(true);
            chk_marker27.setSelected(true);
            chk_marker28.setSelected(true);
            chk_marker29.setSelected(true);
            chk_marker30.setSelected(true);
            chk_marker31.setSelected(true);
            chk_marker32.setSelected(true);
            chk_marker33.setSelected(true);
            chk_marker34.setSelected(true);
            chk_marker35.setSelected(true);
            
        } else {
            chk_marker22.setSelected(false);
            chk_marker23.setSelected(false);
            chk_marker24.setSelected(false);
            chk_marker25.setSelected(false);
            chk_marker26.setSelected(false);
            chk_marker27.setSelected(false);
            chk_marker28.setSelected(false);
            chk_marker29.setSelected(false);
            chk_marker30.setSelected(false);
            chk_marker31.setSelected(false);
            chk_marker32.setSelected(false);
            chk_marker33.setSelected(false);
            chk_marker34.setSelected(false);
            chk_marker35.setSelected(false);
        }
    }//GEN-LAST:event_chk_myeloActionPerformed

    private void chk_nonlinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chk_nonlinActionPerformed
        if (chk_nonlin.isSelected()){
            chk_marker36.setSelected(true);
            chk_marker37.setSelected(true);
            chk_marker38.setSelected(true);
            chk_marker39.setSelected(true);
            chk_marker40.setSelected(true);
            chk_marker41.setSelected(true);
            chk_marker42.setSelected(true);
            chk_marker43.setSelected(true);
            chk_marker44.setSelected(true);
            chk_marker45.setSelected(true);
            chk_marker46.setSelected(true);
            chk_marker47.setSelected(true);
            chk_marker48.setSelected(true);
            chk_marker49.setSelected(true);
        } else {
            chk_marker36.setSelected(false);
            chk_marker37.setSelected(false);
            chk_marker38.setSelected(false);
            chk_marker39.setSelected(false);
            chk_marker40.setSelected(false);
            chk_marker41.setSelected(false);
            chk_marker42.setSelected(false);
            chk_marker43.setSelected(false);
            chk_marker44.setSelected(false);
            chk_marker45.setSelected(false);
            chk_marker46.setSelected(false);
            chk_marker47.setSelected(false);
            chk_marker48.setSelected(false);
            chk_marker49.setSelected(false);
        }
    }//GEN-LAST:event_chk_nonlinActionPerformed

    private void btn_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_saveActionPerformed
        String dp = this.defaultPath;    //JOptionPane.showMessageDialog(null, dp);  //TEST
        String out_fileString = null;
        Ini ini;
        
        try {
            JFileChooser fileChooser = new JFileChooser(dp);
            fileChooser.setFileFilter(new FileNameExtensionFilter(".txt","txt"));
            if (fileChooser.showSaveDialog(jPanel1) == JFileChooser.APPROVE_OPTION) {
                File out_file = fileChooser.getSelectedFile();             
                String filename = fileChooser.getSelectedFile().toString();
                if (!filename.endsWith(".txt")){
                    out_file = new File(out_file + ".txt");
                }
                out_fileString = out_file.toString();
                out_file.createNewFile();
            }
            //JOptionPane.showMessageDialog(null, out_fileString);  //TEST
            ini = new Ini(new File(out_fileString));
            my_log.logger.info("saving query:\t"+out_fileString);
            
            // get info from which frame te data comes from
            String method = this.getAccessibleContext().getAccessibleName();  
            ini.put("frame", "frame", method);
 
            // get data from fields & buttons
            // setting
            String setting = txt_nameSetting.getText();
            ini.put("setting_name", "setting", setting);
            
            // B-lymphoid		
            boolean chk1 = chk_marker1.isSelected();	//	CD19
            boolean chk2 = chk_marker2.isSelected();	//	iCD22
            boolean chk3 = chk_marker3.isSelected();	//	iCD79a
            boolean chk4 = chk_marker4.isSelected();	//	CD10
            boolean chk5 = chk_marker5.isSelected();	//	CD20
            boolean chk6 = chk_marker6.isSelected();	//	CD22
            boolean chk7 = chk_marker7.isSelected();	//	CD24
            boolean chk8 = chk_marker8.isSelected();	//	CRLF2
            boolean chk9 = chk_marker9.isSelected();	//	iIgM
            boolean chk10 = chk_marker10.isSelected();	//	ikappa
            boolean chk11 = chk_marker11.isSelected();	//	ilambda
            ini.put("B_lymph", "CD19", chk1);
            ini.put("B_lymph", "iCD22", chk2);
            ini.put("B_lymph", "iCD79a", chk3);
            ini.put("B_lymph", "CD10", chk4);
            ini.put("B_lymph", "CD20", chk5);
            ini.put("B_lymph", "CD22", chk6);
            ini.put("B_lymph", "CD24", chk7);
            ini.put("B_lymph", "CRLF2", chk8);
            ini.put("B_lymph", "iIgM", chk9);
            ini.put("B_lymph", "ikappa", chk10);
            ini.put("B_lymph", "ilambda", chk11);
            
            // T-Lymphoid		
            boolean chk12 = chk_marker12.isSelected();	//	iCD3
            boolean chk13 = chk_marker13.isSelected();	//	CD7
            boolean chk14 = chk_marker14.isSelected();	//	CD2
            boolean chk15 = chk_marker15.isSelected();	//	CD5
            boolean chk16 = chk_marker16.isSelected();	//	CD1a
            boolean chk17 = chk_marker17.isSelected();	//	sCD3
            boolean chk18 = chk_marker18.isSelected();	//	CD4
            boolean chk19 = chk_marker19.isSelected();	//	CD8
            boolean chk20 = chk_marker20.isSelected();	//	TCRab
            boolean chk21 = chk_marker21.isSelected();	//	TCRgd
            ini.put("T_lymph", "iCD3", chk12);
            ini.put("T_lymph", "CD7", chk13);
            ini.put("T_lymph", "CD2", chk14);
            ini.put("T_lymph", "CD5", chk15);
            ini.put("T_lymph", "CD1a", chk16);
            ini.put("T_lymph", "sCD3", chk17);
            ini.put("T_lymph", "CD4", chk18);
            ini.put("T_lymph", "CD8", chk19);
            ini.put("T_lymph", "TCRab", chk20);
            ini.put("T_lymph", "TCRgd", chk21);

            // myeloisch		
            boolean chk22 = chk_marker22.isSelected();	//	MPO
            boolean chk23 = chk_marker23.isSelected();	//	LZ
            boolean chk24 = chk_marker24.isSelected();	//	CD117
            boolean chk25 = chk_marker25.isSelected();	//	CD13
            boolean chk26 = chk_marker26.isSelected();	//	CD33
            boolean chk27 = chk_marker27.isSelected();	//	CD15
            boolean chk28 = chk_marker28.isSelected();	//	CD65
            boolean chk29 = chk_marker29.isSelected();	//	CD14
            boolean chk30 = chk_marker30.isSelected();	//	CD11c
            boolean chk31 = chk_marker31.isSelected();	//	CD64
            boolean chk32 = chk_marker32.isSelected();	//	CD41
            boolean chk33 = chk_marker33.isSelected();	//	CD61
            boolean chk34 = chk_marker34.isSelected();	//	CD71
            boolean chk35 = chk_marker35.isSelected();	//	CD133
            ini.put("myeloisch", "MPO", chk22);
            ini.put("myeloisch", "LZ", chk23);
            ini.put("myeloisch", "CD117", chk24);
            ini.put("myeloisch", "CD13", chk25);
            ini.put("myeloisch", "CD33", chk26);
            ini.put("myeloisch", "CD15", chk27);
            ini.put("myeloisch", "CD65", chk28);
            ini.put("myeloisch", "CD14", chk29);
            ini.put("myeloisch", "CD11c", chk30);
            ini.put("myeloisch", "CD64", chk31);
            ini.put("myeloisch", "CD41", chk32);
            ini.put("myeloisch", "CD61", chk33);
            ini.put("myeloisch", "CD71", chk34);
            ini.put("myeloisch", "CD133", chk35);
            
            // non-lineage		
            boolean chk36 = chk_marker36.isSelected();	//	CD34
            boolean chk37 = chk_marker37.isSelected();	//	CD38
            boolean chk38 = chk_marker38.isSelected();	//	CD45
            boolean chk39 = chk_marker39.isSelected();	//	HLADR
            boolean chk40 = chk_marker40.isSelected();	//	CD11a
            boolean chk41 = chk_marker41.isSelected();	//	CD11b
            boolean chk42 = chk_marker42.isSelected();	//	CD36
            boolean chk43 = chk_marker43.isSelected();	//	CD44
            boolean chk44 = chk_marker44.isSelected();	//	CD56
            boolean chk45 = chk_marker45.isSelected();	//	CD99
            boolean chk46 = chk_marker46.isSelected();	//	CD123
            boolean chk47 = chk_marker47.isSelected();	//	CD184
            boolean chk48 = chk_marker48.isSelected();	//	NG2
            boolean chk49 = chk_marker49.isSelected();	//	CD371
            ini.put("non_lineage", "CD34", chk36);
            ini.put("non_lineage", "CD38", chk37);
            ini.put("non_lineage", "CD45", chk38);
            ini.put("non_lineage", "HLADR", chk39);
            ini.put("non_lineage", "CD11a", chk40);
            ini.put("non_lineage", "CD11b", chk41);
            ini.put("non_lineage", "CD36", chk42);
            ini.put("non_lineage", "CD44", chk43);
            ini.put("non_lineage", "CD56", chk44);
            ini.put("non_lineage", "CD99", chk45);
            ini.put("non_lineage", "CD123", chk46);
            ini.put("non_lineage", "CD184", chk47);
            ini.put("non_lineage", "NG2", chk48);
            ini.put("non_lineage", "CD371", chk49);
            ini.store();
            
        } catch (IOException ex) {
            Logger.getLogger(SetConnection.class.getName()).log(Level.SEVERE, null, ex);
            my_log.logger.warning("ERROR: " + ex);
        }        
    }//GEN-LAST:event_btn_saveActionPerformed

    private void btn_loadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_loadActionPerformed
String dp = this.defaultPath; 
        String in_fileString = null;
        Ini ini;
        
        try {
            ini = new Ini(new File(personalConfig));        //toggle

            JFileChooser fileChooser = new JFileChooser(dp);
            fileChooser.setFileFilter(new FileNameExtensionFilter(".txt","txt"));
            if (fileChooser.showOpenDialog(jPanel1) == JFileChooser.APPROVE_OPTION) {
                File in_file = fileChooser.getSelectedFile();
                in_fileString = in_file.toString();
            }

            ini = new Ini(new File(in_fileString));
            my_log.logger.info("loading saved query:\t"+in_fileString);
            
            String method = ini.get("frame", "frame");
            //JOptionPane.showMessageDialog(null,method); //TEST
            
            if (method == null || method.isEmpty()) { 
                JOptionPane.showMessageDialog(null, "You are trying to load a wrong frame format!");
            }
            
            if (method.contains("SelectMarker")) {
                // setting
                String setting = ini.get("setting_name", "setting");
                txt_nameSetting.setText(setting);

                // B-lymphoid		
                boolean chk1 = Boolean.parseBoolean(ini.get("B_lymph", "CD19"));
                chk_marker1.setSelected(chk1);	//	CD19
                boolean chk2 = Boolean.parseBoolean(ini.get("B_lymph", "iCD22"));
                chk_marker2.setSelected(chk2);	//	iCD22
                boolean chk3 = Boolean.parseBoolean(ini.get("B_lymph", "iCD79a"));
                chk_marker3.setSelected(chk3);	//	iCD79a
                boolean chk4 = Boolean.parseBoolean(ini.get("B_lymph", "CD10"));
                chk_marker4.setSelected(chk4);	//	CD10
                boolean chk5 = Boolean.parseBoolean(ini.get("B_lymph", "CD20"));
                chk_marker5.setSelected(chk5);	//	CD20
                boolean chk6 = Boolean.parseBoolean(ini.get("B_lymph", "CD22"));
                chk_marker6.setSelected(chk6);	//	CD22
                boolean chk7 = Boolean.parseBoolean(ini.get("B_lymph", "CD24"));
                chk_marker7.setSelected(chk7);	//	CD24
                boolean chk8 = Boolean.parseBoolean(ini.get("B_lymph", "CRLF2"));
                chk_marker8.setSelected(chk8);	//	CRLF2
                boolean chk9 = Boolean.parseBoolean(ini.get("B_lymph", "iIgM"));
                chk_marker9.setSelected(chk9);	//	iIgM
                boolean chk10 = Boolean.parseBoolean(ini.get("B_lymph", "ikappa"));
                chk_marker10.setSelected(chk10);	//	ikappa
                boolean chk11 = Boolean.parseBoolean(ini.get("B_lymph", "ilambda"));
                chk_marker11.setSelected(chk11);	//	ilambda

                // T-Lymphoid		
                boolean chk12 = Boolean.parseBoolean(ini.get("T_lymph", "iCD3"));
                chk_marker12.setSelected(chk12);	//	iCD3
                boolean chk13 = Boolean.parseBoolean(ini.get("T_lymph", "CD7"));
                chk_marker13.setSelected(chk13);	//	CD7
                boolean chk14 = Boolean.parseBoolean(ini.get("T_lymph", "CD2"));
                chk_marker14.setSelected(chk14);	//	CD2
                boolean chk15 = Boolean.parseBoolean(ini.get("T_lymph", "CD5"));
                chk_marker15.setSelected(chk15);	//	CD5
                boolean chk16 = Boolean.parseBoolean(ini.get("T_lymph", "CD1a"));
                chk_marker16.setSelected(chk16);	//	CD1a
                boolean chk17 = Boolean.parseBoolean(ini.get("T_lymph", "sCD3"));
                chk_marker17.setSelected(chk17);	//	sCD3
                boolean chk18 = Boolean.parseBoolean(ini.get("T_lymph", "CD4"));
                chk_marker18.setSelected(chk18);	//	CD4
                boolean chk19 = Boolean.parseBoolean(ini.get("T_lymph", "CD8"));
                chk_marker19.setSelected(chk19);	//	CD8
                boolean chk20 = Boolean.parseBoolean(ini.get("T_lymph", "TCRab"));
                chk_marker20.setSelected(chk20);	//	TCRab
                boolean chk21 = Boolean.parseBoolean(ini.get("T_lymph", "TCRgd"));
                chk_marker21.setSelected(chk21);	//	TCRgd

                // myeloisch		
                boolean chk22 = Boolean.parseBoolean(ini.get("myeloisch", "MPO"));
                chk_marker22.setSelected(chk22);	//	MPO
                boolean chk23 = Boolean.parseBoolean(ini.get("myeloisch", "LZ"));
                chk_marker23.setSelected(chk23);	//	LZ
                boolean chk24 = Boolean.parseBoolean(ini.get("myeloisch", "CD117"));
                chk_marker24.setSelected(chk24);	//	CD117
                boolean chk25 = Boolean.parseBoolean(ini.get("myeloisch", "CD13"));
                chk_marker25.setSelected(chk25);	//	CD13
                boolean chk26 = Boolean.parseBoolean(ini.get("myeloisch", "CD33"));
                chk_marker26.setSelected(chk26);	//	CD33
                boolean chk27 = Boolean.parseBoolean(ini.get("myeloisch", "CD15"));
                chk_marker27.setSelected(chk27);	//	CD15
                boolean chk28 = Boolean.parseBoolean(ini.get("myeloisch", "CD65"));
                chk_marker28.setSelected(chk28);	//	CD65
                boolean chk29 = Boolean.parseBoolean(ini.get("myeloisch", "CD14"));
                chk_marker29.setSelected(chk29);	//	CD14
                boolean chk30 = Boolean.parseBoolean(ini.get("myeloisch", "CD11c"));
                chk_marker30.setSelected(chk30);	//	CD11c
                boolean chk31 = Boolean.parseBoolean(ini.get("myeloisch", "CD64"));
                chk_marker31.setSelected(chk31);	//	CD64
                boolean chk32 = Boolean.parseBoolean(ini.get("myeloisch", "CD41"));
                chk_marker32.setSelected(chk32);	//	CD41
                boolean chk33 = Boolean.parseBoolean(ini.get("myeloisch", "CD61"));
                chk_marker33.setSelected(chk33);	//	CD61
                boolean chk34 = Boolean.parseBoolean(ini.get("myeloisch", "CD71"));
                chk_marker34.setSelected(chk34);	//	CD71
                boolean chk35 = Boolean.parseBoolean(ini.get("myeloisch", "CD133"));
                chk_marker35.setSelected(chk35);	//	CD133

                // non-lineage		
                boolean chk36 = Boolean.parseBoolean(ini.get("non_lineage", "CD34"));
                chk_marker36.setSelected(chk36);	//	CD34
                boolean chk37 = Boolean.parseBoolean(ini.get("non_lineage", "CD38"));
                chk_marker37.setSelected(chk37);	//	CD38
                boolean chk38 = Boolean.parseBoolean(ini.get("non_lineage", "CD45"));
                chk_marker38.setSelected(chk38);	//	CD45
                boolean chk39 = Boolean.parseBoolean(ini.get("non_lineage", "HLADR"));
                chk_marker39.setSelected(chk39);	//	HLADR
                boolean chk40 = Boolean.parseBoolean(ini.get("non_lineage", "CD11a"));
                chk_marker40.setSelected(chk40);	//	CD11a
                boolean chk41 = Boolean.parseBoolean(ini.get("non_lineage", "CD11b"));
                chk_marker41.setSelected(chk41);	//	CD11b
                boolean chk42 = Boolean.parseBoolean(ini.get("non_lineage", "CD36"));
                chk_marker42.setSelected(chk42);	//	CD36
                boolean chk43 = Boolean.parseBoolean(ini.get("non_lineage", "CD44"));
                chk_marker43.setSelected(chk43);	//	CD44
                boolean chk44 = Boolean.parseBoolean(ini.get("non_lineage", "CD56"));
                chk_marker44.setSelected(chk44);	//	CD56
                boolean chk45 = Boolean.parseBoolean(ini.get("non_lineage", "CD99"));
                chk_marker45.setSelected(chk45);	//	CD99
                boolean chk46 = Boolean.parseBoolean(ini.get("non_lineage", "CD123"));
                chk_marker46.setSelected(chk46);	//	CD123
                boolean chk47 = Boolean.parseBoolean(ini.get("non_lineage", "CD184"));
                chk_marker47.setSelected(chk47);	//	CD184
                boolean chk48 = Boolean.parseBoolean(ini.get("non_lineage", "NG2"));
                chk_marker48.setSelected(chk48);	//	NG2
                boolean chk49 = Boolean.parseBoolean(ini.get("non_lineage", "CD371"));
                chk_marker49.setSelected(chk49);	//	CD371
                
            } else {
                JOptionPane.showMessageDialog(null, "You are trying to load a wrong frame format!");
                my_log.logger.warning("ERROR: trying to load wrong frame format!");
            }
        } catch (IOException ex) {
            Logger.getLogger(SetConnection.class.getName()).log(Level.SEVERE, null, ex);
            my_log.logger.warning("ERROR: "+ex);
        }
        
        
    }//GEN-LAST:event_btn_loadActionPerformed

    private void btn_clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clearActionPerformed
        chk_Blymph.setSelected(false);
        chk_marker1.setSelected(false);
        chk_marker2.setSelected(false);
        chk_marker3.setSelected(false);
        chk_marker4.setSelected(false);
        chk_marker5.setSelected(false);
        chk_marker6.setSelected(false);
        chk_marker7.setSelected(false);
        chk_marker8.setSelected(false);
        chk_marker9.setSelected(false);
        chk_marker10.setSelected(false);
        chk_marker11.setSelected(false);

        chk_Tlymph.setSelected(false);
        chk_marker12.setSelected(false);
        chk_marker13.setSelected(false);
        chk_marker14.setSelected(false);
        chk_marker15.setSelected(false);
        chk_marker16.setSelected(false);
        chk_marker17.setSelected(false);
        chk_marker18.setSelected(false);
        chk_marker19.setSelected(false);
        chk_marker20.setSelected(false);
        chk_marker21.setSelected(false);

        chk_myelo.setSelected(false);
        chk_marker22.setSelected(false);
        chk_marker23.setSelected(false);
        chk_marker24.setSelected(false);
        chk_marker25.setSelected(false);
        chk_marker26.setSelected(false);
        chk_marker27.setSelected(false);
        chk_marker28.setSelected(false);
        chk_marker29.setSelected(false);
        chk_marker30.setSelected(false);
        chk_marker31.setSelected(false);
        chk_marker32.setSelected(false);
        chk_marker33.setSelected(false);
        chk_marker34.setSelected(false);
        chk_marker35.setSelected(false);

        chk_nonlin.setSelected(false);
        chk_marker36.setSelected(false);
        chk_marker37.setSelected(false);
        chk_marker38.setSelected(false);
        chk_marker39.setSelected(false);
        chk_marker40.setSelected(false);
        chk_marker41.setSelected(false);
        chk_marker42.setSelected(false);
        chk_marker43.setSelected(false);
        chk_marker44.setSelected(false);
        chk_marker45.setSelected(false);
        chk_marker46.setSelected(false);
        chk_marker47.setSelected(false);
        chk_marker48.setSelected(false);
        chk_marker49.setSelected(false);

        txt_nameSetting.setText("");
        markerSql = null;
    }//GEN-LAST:event_btn_clearActionPerformed

    private void btn_setActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_setActionPerformed
        String list = "";
        if (chk_marker1.isSelected()){ list = list +"'"+ chk_marker1.getText() + "',";}	
        if (chk_marker2.isSelected()){ list = list +"'"+ chk_marker2.getText() + "',";}
        if (chk_marker3.isSelected()){ list = list +"'"+ chk_marker3.getText() + "',";}
        if (chk_marker4.isSelected()){ list = list +"'"+ chk_marker4.getText() + "',";}
        if (chk_marker5.isSelected()){ list = list +"'"+ chk_marker5.getText() + "',";}
        if (chk_marker6.isSelected()){ list = list +"'"+ chk_marker6.getText() + "',";}
        if (chk_marker7.isSelected()){ list = list +"'"+ chk_marker7.getText() + "',";}
        if (chk_marker8.isSelected()){ list = list +"'"+ chk_marker8.getText() + "',";}
        if (chk_marker9.isSelected()){ list = list +"'"+ chk_marker9.getText() + "',";}
        if (chk_marker10.isSelected()){ list = list +"'"+ chk_marker10.getText() + "',";}
        if (chk_marker11.isSelected()){ list = list +"'"+ chk_marker11.getText() + "',";}
        
        if (chk_marker12.isSelected()){ list = list +"'"+ chk_marker12.getText() + "',";}
        if (chk_marker13.isSelected()){ list = list +"'"+ chk_marker13.getText() + "',";}
        if (chk_marker14.isSelected()){ list = list +"'"+ chk_marker14.getText() + "',";}
        if (chk_marker15.isSelected()){ list = list +"'"+ chk_marker15.getText() + "',";}
        if (chk_marker16.isSelected()){ list = list +"'"+ chk_marker16.getText() + "',";}
        if (chk_marker17.isSelected()){ list = list +"'"+ chk_marker17.getText() + "',";}
        if (chk_marker18.isSelected()){ list = list +"'"+ chk_marker18.getText() + "',";}
        if (chk_marker19.isSelected()){ list = list +"'"+ chk_marker19.getText() + "',";}
        if (chk_marker20.isSelected()){ list = list +"'"+ chk_marker20.getText() + "',";}
        if (chk_marker21.isSelected()){ list = list +"'"+ chk_marker21.getText() + "',";}
        
        if (chk_marker22.isSelected()){ list = list +"'"+ chk_marker22.getText() + "',";}
        if (chk_marker23.isSelected()){ list = list +"'"+ chk_marker23.getText() + "',";}
        if (chk_marker24.isSelected()){ list = list +"'"+ chk_marker24.getText() + "',";}
        if (chk_marker25.isSelected()){ list = list +"'"+ chk_marker25.getText() + "',";}
        if (chk_marker26.isSelected()){ list = list +"'"+ chk_marker26.getText() + "',";}
        if (chk_marker27.isSelected()){ list = list +"'"+ chk_marker27.getText() + "',";}
        if (chk_marker28.isSelected()){ list = list +"'"+ chk_marker28.getText() + "',";}
        if (chk_marker29.isSelected()){ list = list +"'"+ chk_marker29.getText() + "',";}
        if (chk_marker30.isSelected()){ list = list +"'"+ chk_marker30.getText() + "',";}
        if (chk_marker31.isSelected()){ list = list +"'"+ chk_marker31.getText() + "',";}
        if (chk_marker32.isSelected()){ list = list +"'"+ chk_marker32.getText() + "',";}
        if (chk_marker33.isSelected()){ list = list +"'"+ chk_marker33.getText() + "',";}
        if (chk_marker34.isSelected()){ list = list +"'"+ chk_marker34.getText() + "',";}
        if (chk_marker35.isSelected()){ list = list +"'"+ chk_marker35.getText() + "',";}
        
        if (chk_marker36.isSelected()){ list = list +"'"+ chk_marker36.getText() + "',";}
        if (chk_marker37.isSelected()){ list = list +"'"+ chk_marker37.getText() + "',";}
        if (chk_marker38.isSelected()){ list = list +"'"+ chk_marker38.getText() + "',";}
        if (chk_marker39.isSelected()){ list = list +"'"+ chk_marker39.getText() + "',";}
        if (chk_marker40.isSelected()){ list = list +"'"+ chk_marker40.getText() + "',";}
        if (chk_marker41.isSelected()){ list = list +"'"+ chk_marker41.getText() + "',";}
        if (chk_marker42.isSelected()){ list = list +"'"+ chk_marker42.getText() + "',";}
        if (chk_marker43.isSelected()){ list = list +"'"+ chk_marker43.getText() + "',";}
        if (chk_marker44.isSelected()){ list = list +"'"+ chk_marker44.getText() + "',";}
        if (chk_marker45.isSelected()){ list = list +"'"+ chk_marker45.getText() + "',";}
        if (chk_marker46.isSelected()){ list = list +"'"+ chk_marker46.getText() + "',";}
        if (chk_marker47.isSelected()){ list = list +"'"+ chk_marker47.getText() + "',";}
        if (chk_marker48.isSelected()){ list = list +"'"+ chk_marker48.getText() + "',";}
        if (chk_marker49.isSelected()){ list = list +"'"+ chk_marker49.getText() + "',";}

        list = list.substring(0, (list.length() - 1));
        markerSql= " AND marker_name in ("+list+")";
        
        //JOptionPane.showMessageDialog(null, markerSql);  //TEST
    }//GEN-LAST:event_btn_setActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SelectMarker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SelectMarker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SelectMarker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SelectMarker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SelectMarker().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_clear;
    private javax.swing.JButton btn_load;
    private javax.swing.JButton btn_save;
    private javax.swing.JButton btn_set;
    private javax.swing.JCheckBox chk_Blymph;
    private javax.swing.JCheckBox chk_Tlymph;
    private javax.swing.JCheckBox chk_marker1;
    private javax.swing.JCheckBox chk_marker10;
    private javax.swing.JCheckBox chk_marker11;
    private javax.swing.JCheckBox chk_marker12;
    private javax.swing.JCheckBox chk_marker13;
    private javax.swing.JCheckBox chk_marker14;
    private javax.swing.JCheckBox chk_marker15;
    private javax.swing.JCheckBox chk_marker16;
    private javax.swing.JCheckBox chk_marker17;
    private javax.swing.JCheckBox chk_marker18;
    private javax.swing.JCheckBox chk_marker19;
    private javax.swing.JCheckBox chk_marker2;
    private javax.swing.JCheckBox chk_marker20;
    private javax.swing.JCheckBox chk_marker21;
    private javax.swing.JCheckBox chk_marker22;
    private javax.swing.JCheckBox chk_marker23;
    private javax.swing.JCheckBox chk_marker24;
    private javax.swing.JCheckBox chk_marker25;
    private javax.swing.JCheckBox chk_marker26;
    private javax.swing.JCheckBox chk_marker27;
    private javax.swing.JCheckBox chk_marker28;
    private javax.swing.JCheckBox chk_marker29;
    private javax.swing.JCheckBox chk_marker3;
    private javax.swing.JCheckBox chk_marker30;
    private javax.swing.JCheckBox chk_marker31;
    private javax.swing.JCheckBox chk_marker32;
    private javax.swing.JCheckBox chk_marker33;
    private javax.swing.JCheckBox chk_marker34;
    private javax.swing.JCheckBox chk_marker35;
    private javax.swing.JCheckBox chk_marker36;
    private javax.swing.JCheckBox chk_marker37;
    private javax.swing.JCheckBox chk_marker38;
    private javax.swing.JCheckBox chk_marker39;
    private javax.swing.JCheckBox chk_marker4;
    private javax.swing.JCheckBox chk_marker40;
    private javax.swing.JCheckBox chk_marker41;
    private javax.swing.JCheckBox chk_marker42;
    private javax.swing.JCheckBox chk_marker43;
    private javax.swing.JCheckBox chk_marker44;
    private javax.swing.JCheckBox chk_marker45;
    private javax.swing.JCheckBox chk_marker46;
    private javax.swing.JCheckBox chk_marker47;
    private javax.swing.JCheckBox chk_marker48;
    private javax.swing.JCheckBox chk_marker49;
    private javax.swing.JCheckBox chk_marker5;
    private javax.swing.JCheckBox chk_marker6;
    private javax.swing.JCheckBox chk_marker7;
    private javax.swing.JCheckBox chk_marker8;
    private javax.swing.JCheckBox chk_marker9;
    private javax.swing.JCheckBox chk_myelo;
    private javax.swing.JCheckBox chk_nonlin;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel lbl_selName;
    private javax.swing.JTextField txt_nameSetting;
    // End of variables declaration//GEN-END:variables
}
